version: '3'
services:
  drawingbed-server:
    container_name: drawingbed-server
    build: .
    working_dir: /work
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6688:8080
    volumes:
      - ./data/images:/images
    entrypoint: ["java","-Dspring.profiles.active=aliyun","-jar","/work/target/drawingbed-0.0.1-SNAPSHOT.jar"]